services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.slim  # Use slim if exists
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Hot-reload code changes
      - ./backend/model:/app/model  # Persistent fine-tuned weights
    environment:
      - PYTHONPATH=/app
      - UVICORN_RELOAD=true  # Critical for --reload to work

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped