services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.slim  
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  
      - ./backend/model:/app/model  
    environment:
      - PYTHONPATH=/app
      - UVICORN_RELOAD=true 
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped