# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.slim
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    command: sh -c "mkdir -p /app/model && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
      - MODEL_PATH=cardiffnlp/twitter-roberta-base-sentiment-latest
      - FRAMEWORK=pt
      - QUANTIZE=false
      - HOT_RELOAD=true
      - LOG_LEVEL=INFO
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped